<?php
/**
* @package real/evrazplace
* @author Josh Carswell <jcarswell@evrazplace.com>
* @copyright 2018 The Regina Exhibition Association Ltd.
*/
?>

<p><span class="about-title">Evraz Place</span><br />
    1700 Elphinstone Street <br />
    Regina, Saskatchewan S4P 2Z6<br />
    Canada<br /><br />
    Credit Card Statment: EVRAZ PLACE-GENERAL<br />
    All Currency is in Canadian Dollors (CAD)
</p>
